//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZY_CDMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZY_CDMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your License not Valid.
        /// </summary>
        public static string activationneeded {
            get {
                return ResourceManager.GetString("activationneeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Added Successfully.
        /// </summary>
        public static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Dealers Mangment System.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام إدارة محلات تجارة وصيانة السيارات.
        /// </summary>
        public static string AppNameAR {
            get {
                return ResourceManager.GetString("AppNameAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V 1.0.0.0.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string AZversion {
            get {
                return ResourceManager.GetString("AZversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Canceled Operation.
        /// </summary>
        public static string CancelByUser {
            get {
                return ResourceManager.GetString("CancelByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Operation.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto2020.
        /// </summary>
        public static string dbnamecon {
            get {
                return ResourceManager.GetString("dbnamecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Type Digit Only .
        /// </summary>
        public static string digitOnlyError {
            get {
                return ResourceManager.GetString("digitOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Already Exist.
        /// </summary>
        public static string Exist {
            get {
                return ResourceManager.GetString("Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد الخروج ؟ .
        /// </summary>
        public static string ExitPromtAr {
            get {
                return ResourceManager.GetString("ExitPromtAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to Exit ?.
        /// </summary>
        public static string ExitPromtEng {
            get {
                return ResourceManager.GetString("ExitPromtEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username Or Password.
        /// </summary>
        public static string FaieldLogin {
            get {
                return ResourceManager.GetString("FaieldLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data.
        /// </summary>
        public static string invalidData {
            get {
                return ResourceManager.GetString("invalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string JordanCleaningVersion {
            get {
                return ResourceManager.GetString("JordanCleaningVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZY Technologies Solutions © 2020.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زد واي لحلول تكنولوجيا المعلومات .
        /// </summary>
        public static string LogoAR {
            get {
                return ResourceManager.GetString("LogoAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZY Technologies Solutions.
        /// </summary>
        public static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill Missed Boxes.
        /// </summary>
        public static string missingTextboxes {
            get {
                return ResourceManager.GetString("missingTextboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Source You Need.
        /// </summary>
        public static string Noselection {
            get {
                return ResourceManager.GetString("Noselection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Not Exist.
        /// </summary>
        public static string notExist {
            get {
                return ResourceManager.GetString("notExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zy@admin2021.
        /// </summary>
        public static string passwordcon {
            get {
                return ResourceManager.GetString("passwordcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Activate App.
        /// </summary>
        public static string pleaseActive {
            get {
                return ResourceManager.GetString("pleaseActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MZUBAIDI.
        /// </summary>
        public static string servercon {
            get {
                return ResourceManager.GetString("servercon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Try Again .
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Updated Successfully.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sa.
        /// </summary>
        public static string usernamecon {
            get {
                return ResourceManager.GetString("usernamecon", resourceCulture);
            }
        }
    }
}
