//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZY_CDMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesAR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesAR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZY_CDMS.ResourcesAR", typeof(ResourcesAR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهت الرخضة.
        /// </summary>
        internal static string activationneeded {
            get {
                return ResourceManager.GetString("activationneeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الاضافة بنجاح.
        /// </summary>
        internal static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام إدارة محلات تجارة وصيانة السيارات.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string AZversion {
            get {
                return ResourceManager.GetString("AZversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الغاء العملية من قبل العميل.
        /// </summary>
        internal static string CancelByUser {
            get {
                return ResourceManager.GetString("CancelByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إكتملت العملية.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto2020.
        /// </summary>
        internal static string dbnamecon {
            get {
                return ResourceManager.GetString("dbnamecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يسمح للأرقام فقط.
        /// </summary>
        internal static string digitOnlyError {
            get {
                return ResourceManager.GetString("digitOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجود مسبقا.
        /// </summary>
        internal static string Exist {
            get {
                return ResourceManager.GetString("Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد الخروج ؟ .
        /// </summary>
        internal static string ExitPromt {
            get {
                return ResourceManager.GetString("ExitPromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في كلمة المرور أو اسم المستخدم.
        /// </summary>
        internal static string FaieldLogin {
            get {
                return ResourceManager.GetString("FaieldLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في البيانات المدخلة.
        /// </summary>
        internal static string invalidData {
            get {
                return ResourceManager.GetString("invalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string JordanCleaningVersion {
            get {
                return ResourceManager.GetString("JordanCleaningVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زد واي لحلول تكنولوجيا المعلومات © 2021.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ملىْ البيانات المطلوبة.
        /// </summary>
        internal static string missingTextboxes {
            get {
                return ResourceManager.GetString("missingTextboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بيانات.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إختيار المطلوب.
        /// </summary>
        internal static string Noselection {
            get {
                return ResourceManager.GetString("Noselection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير موجود.
        /// </summary>
        internal static string notExist {
            get {
                return ResourceManager.GetString("notExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string passwordcon {
            get {
                return ResourceManager.GetString("passwordcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء تفعيل التطبيق قبل البدء بالاستخدام .
        /// </summary>
        internal static string pleaseActive {
            get {
                return ResourceManager.GetString("pleaseActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MZUBAIDI.
        /// </summary>
        internal static string servercon {
            get {
                return ResourceManager.GetString("servercon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء المحاولة مرة أخرى.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التحديث بنجاح.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sa.
        /// </summary>
        internal static string usernamecon {
            get {
                return ResourceManager.GetString("usernamecon", resourceCulture);
            }
        }
    }
}
